Fix Crash if Ntrip Node is Launched without Internet
angsa-robotics/ntrip_client pull request #1
Opened 2024-07-02 11:40 UTC by AlboAlby00

It fixes this problem: https://angsa-robotics-team-i7lircnb8klx.atlassian.net/browse/AR-779.
Now the ntrip_client node tries to connect to the NTRIP server every five seconds instead of crashing if there is no internet connection when it is launched.

2024-07-03 07:24 UTC, tonynajjar commented on scripts/ntrip_ros.py
> +    node.wait_for_connection()
```suggestion
    while not node.run():
        self.get_logger().error(f'Retrying in {NTRIPClient.DEFAULT_RECONNECT_ATEMPT_WAIT_SECONDS} seconds.')    
        time.sleep(NTRIPClient.DEFAULT_RECONNECT_ATEMPT_WAIT_SECONDS)
```

Can't it just be like this without anything else?

2024-07-03 07:31 UTC, tonynajjar requested changes
see comment

2024-07-04 06:41 UTC, AlboAlby00 commented on scripts/ntrip_ros.py
> +    node.wait_for_connection()
Yes, it works also like this

2024-07-04 07:16 UTC, AlboAlby00 commented
> see comment

@tonynajjar I've done it.

2024-07-04 15:43 UTC, tonynajjar approved these changes

2024-07-04 15:56 UTC, merged